### PR TITLE
Fix logout errors. Closes #48

### LINKED ISSUE #48: Error on logout
### Version

master

### File / Feature

\-

### Expected behaviour

No errors

### Actual behaviour

Errors happen

### Stacktrace / Error message

2017-08-22-1503385536_screenshot

### Other info

\-

### PR DESCRIPTION
**Pull request by TomOffringa**
Test if you get any errors when logging out (while some listeners are active, refreshing etc.)

### CODE REVIEW

File: src/js/modules/observer/index.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ class ObserverModule {
             // Remove icons.
             this.restorePhonenumbers()
             // Remove our stylesheet.
-            $(this.observer.printStyle).remove()
+            $(this.printStyle).remove();
```
Comment (jvanveen) [inline src/js/modules/observer/index.js]: no semicoln `;`
